import { NextRequest, NextResponse } from "next/server";
import { execFile } from "child_process";
import { guard } from "@/lib/api-guard";
import fs from "fs";
import path from "path";
import os from "os";

// Disable body parsing size limits if necessary, though default Next.js limits are 4MB
export const dynamic = "force-dynamic";

// Hard cap on the audio blob we will spawn a Python process for (DoS guard).
const MAX_AUDIO_BYTES = 25 * 1024 * 1024;

export async function POST(req: NextRequest) {
  // Spawns an external process — rate limit hard.
  const blocked = guard(req, "clean-audio", { limit: 10, windowMs: 60_000 });
  if (blocked) return blocked;

  try {
    const formData = await req.formData();
    const file = formData.get("audio") as File;

    if (file && file.size > MAX_AUDIO_BYTES) {
      return NextResponse.json({ error: "Audio too large. Maximum 25MB." }, { status: 400 });
    }

    if (!file) {
      return NextResponse.json(
        { error: "No audio file provided in the request" },
        { status: 400 }
      );
    }

    // Determine file extension
    const mimeType = file.type || "audio/webm";
    const extension = mimeType.includes("webm") ? ".webm" : mimeType.includes("wav") ? ".wav" : ".ogg";

    const tempDir = os.tmpdir();
    const timestamp = Date.now();
    const inputFilename = `input-${timestamp}${extension}`;
    const outputFilename = `input-${timestamp}.wav`; // python -m df.enhance saves as .wav with empty postfix

    const inputPath = path.join(tempDir, inputFilename);
    const outputPath = path.join(tempDir, outputFilename);

    // Save uploaded file buffer to temp directory
    const buffer = Buffer.from(await file.arrayBuffer());
    await fs.promises.writeFile(inputPath, buffer);

    // Execute DeepFilterNet via execFile — arguments are passed as an array, so
    // there is no shell to interpret metacharacters (no command injection).
    try {
      await new Promise<void>((resolve, reject) => {
        execFile(
          "python",
          ["-m", "df.enhance", "--output-postfix", "", "-o", tempDir, inputPath],
          { timeout: 120_000, maxBuffer: 10 * 1024 * 1024 },
          (error, stdout, stderr) => {
            if (error) {
              console.error("DeepFilterNet execution error details:", stderr || error.message);
              reject(new Error(stderr || error.message));
            } else {
              resolve();
            }
          }
        );
      });

      // Verify the cleaned file exists
      if (!fs.existsSync(outputPath)) {
        throw new Error("Cleaned audio output file was not generated by DeepFilterNet.");
      }

      // Read output file
      const cleanedBuffer = await fs.promises.readFile(outputPath);

      // Clean up temp files in the background
      fs.promises.unlink(inputPath).catch((err) => console.error("Temp input cleanup error:", err));
      fs.promises.unlink(outputPath).catch((err) => console.error("Temp output cleanup error:", err));

      // Return the cleaned WAV audio
      return new NextResponse(cleanedBuffer, {
        headers: {
          "Content-Type": "audio/wav",
          "X-Noise-Suppressed": "DeepFilterNet-Server",
        },
      });

    } catch (cmdError: unknown) {
      const msg = cmdError instanceof Error ? cmdError.message : "DeepFilterNet CLI failed";
      console.warn("df-clean failed or is not installed. Falling back to original audio. Error:", msg);

      // Clean up input temp file
      fs.promises.unlink(inputPath).catch(() => {});

      // Fallback: Send the original audio back but set an error header
      // Do NOT surface `msg` (raw stderr / filesystem paths) to the client.
      return new NextResponse(buffer, {
        headers: {
          "Content-Type": mimeType,
          "X-Noise-Suppressed-Failed": "true",
        },
      });
    }

  } catch (err: unknown) {
    console.error("Error in clean-audio API route:", err);
    const msg = err instanceof Error ? err.message : "Internal Server Error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
